### ISSUE TITLE
upgrade to sbt-assembly v0.13.0

### ISSUE THREAD

**Issue by sokrahta** [socrata-platform/socrata-sbt-plugins#12]
linked from http://notes.implicit.ly/post/112113919424/sbt-assembly-0-13-0
copyed from https://github.com/sbt/sbt-assembly/blob/master/notes/0.13.0.markdown

Accumulate errors during merge
sbt-assembly 0.13.0 now accumulates merge conflict errors and displays them all.
#144 by [@jeffreyolchovy][@jeffreyolchovy].

Improvements
META-INF/mailcap, META-INF/mimetypes.default, and META-INF/maven/ are discarded by default. #145 by @catap

**Comment by velvia** [comment]
Thanks for using issues @sokrahta !
