### ISSUE TITLE
MiMa

### ISSUE THREAD

**Issue by sokrahta** [socrata-platform/socrata-sbt-plugins#13]
Importing from https://github.com/socrata/socrata-cloudbees-sbt/pull/3
## What to do
- integrate MiMa previousArtifact setting with sbt-release
- on failure set build failed and exit
- in the release version commit, set previousVersion for future use
- previousVersion = None is allowed, don't let sbt complain so much
- when previousVersion was None create previousArtifact setting
- ignore previousVersionFile
- breaking changes are binary incompatible, so use previousVersion = None to stop checks
## Puzzles

Does it make sense for MIMA to be enforced for all repos?  We use sbt-release for stuff like soda-fountain as well.
Hm, no it doesn't really.  I don't see why you'd use sbt-release for non-library projects there.  Surely it's better for non-libraries to have a (goal of a) continuous release cycle where EVERY commit is a
potential release?

**Comment by velvia** [comment]
I think until we get to a world where for non-library projects, we can
deploy continuously, sbt-release will continue to make sense.  So, until
then, I don't think we should mandate MIMA for all repos.

On Thu, Feb 26, 2015 at 3:25 PM, John Krah <notifications@github.com> wrote:

> Importing from socrata/socrata-cloudbees-sbt#3
> <https://github.com/socrata/socrata-cloudbees-sbt/pull/3>
> What to do
>
>    - integrate MiMa previousArtifact setting with sbt-release
>    - on failure set build failed and exit
>    - in the release version commit, set previousVersion for future use
>    - previousVersion = None is allowed, don't let sbt complain so much
>    - when previousVersion was None create previousArtifact setting
>    - ignore previousVersionFile
>    - breaking changes are binary incompatible, so use previousVersion =
>    None to stop checks
>
> Puzzles
>
> Does it make sense for MIMA to be enforced for all repos? We use
> sbt-release for stuff like soda-fountain as well.
> Hm, no it doesn't really. I don't see why you'd use sbt-release for
> non-library projects there. Surely it's better for non-libraries to have a
> (goal of a) continuous release cycle where EVERY commit is a
> potential release?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/socrata/socrata-sbt-plugins/issues/13>.
>



-- 
Evan Chan   |   Principal Engineer, Socrata     |    @evanfchan
*Socrata <http://www.socrata.com/> *| The Data Experience Company™
*Socrata isn't about worldly success, but about changing the world
successfully. This is why I'm excited to be here.*
*What does Socrata do? <https://www.youtube.com/watch?v=yyz86MlkriQ> *(watch
our 2 min video)
