### ISSUE TITLE
??? vs NotImplemented

### ISSUE THREAD

**Issue by sokrahta** [socrata-platform/socrata-sbt-plugins#15]
@kaidamasaki suggests that ??? is bad style and should be prohibited.

**Comment by kaidamasaki** [comment]
I think it's a good idea to have it at least warn, since it generally means someone was sketching something and didn't finish.

**Comment by clint-tseng** [comment]
I think Kaida is being a killjoy and ??? is the funnest feature ever. :)

**Comment by rjmac** [comment]
I still think everyone should have
```scala
def ಠ_ಠ = ???
```
in their stdlib.

**Comment by sokrahta** [comment]
fixed in #25
