### ISSUE TITLE
Super Safe

### ISSUE THREAD

**Issue by sokrahta** [socrata-platform/socrata-sbt-plugins#19]
investigate Super Safe plugin
# 

Thanks.  Most likely we may add this to our internal plugins project, let the license live on our build server and then dev's could run the limited version as needed.  

Let me play with it some and get back with some feedback.  This is awesome stuff.

On Tue, Mar 10, 2015 at 12:55 PM, Bill Venners bill@artima.com wrote:

```
Hi Marc,

On Tue, Mar 10, 2015 at 12:49 PM, Marc Millstone <millstone@gmail.com> wrote:
> This looks great.  Is the 60$ per year per project? Per team?  Per company?
>
It is per "seat" per year, where a seat is either a developer or a
continuous integration server. But there's also a clause in the
license agreement that allows anyone to use it for free without a
licence key, and in such cases it will operate with reduced features.
That allows you to include SuperSafe in your build and just buy a
license key for one developer if you want. Everyone else would just be
running it in reduced feature mode. That one person might have to fix
other people's bugs from time to time, but depending on how that goes
it might be fine for some teams. The full legalese is here:

http://www.artima.com/supersafe_license.html

In the future we plan to offer a site license also, but we don't have
that yet. Let me know if you have other questions.

Bill

> On Tue, Mar 10, 2015 at 12:31 PM, Bill Venners <bill@artima.com> wrote:
>>
>> Hi Marc,
>>
>> We'd like to invite you to try our latest software tool for Scala
>> developers, Artima SuperSafe, free for thirty days. SuperSafe goes where no
>> developer tool has gone before: it is the first compiler plugin that
>> eliminates equality comparison bugs in Scala programs. It will save you time
>> and money by ensuring certain kinds of defects don't escape past the compile
>> phase. And to thank you for trying SuperSafe, we'll also give you a 50%
>> discount coupon for Artima's Scala books.
>>
>> Even if you decide not to license SuperSafe long term, you can use it for
>> a month for free to seek out bugs in your Scala projects. Just click on the
>> big blue button on this page to download a license file (and get the
>> discount on books):
>>
>> http://www.artima.com/supersafe_vip?n=0dWSsFO5GE
>>
>> Thanks.
>>
>> Bill
>> ----
>> Bill Venners
>> President, Artima, Inc.
>>
>> You are receiving this email because you either subscribed to Artima
>> Marketplace mailing list or made a Scala-related purchase at Artima.com
>> under the Artima ID, 76402. You can edit your email preferences at the
>> settings page of your Artima.com user account:
>> http://www.artima.com/account, or you can unsubscribe from this mailing list
>> here: http://www.artima.com/account/unsubscribe?n=08xI48G7FD.
>>
>> If you have any trouble unsubscribing via the above process, please email
>> us at unsubscribe-help@artima.com and a real human being will make sure you
>> get unsubscribed.
>>
>> Artima, Inc.
>> 2070 N Broadway #305
>> Walnut Creek, CA 94597, USA
>> http://www.artima.com
```

**Comment by velvia** [comment]
Super Safe does look interesting, but the $ not sure if it's worth it just
for equality checking.  If they packaged up a lot more checks I think it'd
be more worth it.

On Fri, Mar 13, 2015 at 4:02 PM, John Krah <notifications@github.com> wrote:

> investigate Super Safe plugin
>
> Thanks. Most likely we may add this to our internal plugins project, let
> the license live on our build server and then dev's could run the limited
> version as needed.
>
> Let me play with it some and get back with some feedback. This is awesome
> stuff.
>
> On Tue, Mar 10, 2015 at 12:55 PM, Bill Venners bill@artima.com wrote:
>
> Hi Marc,
>
> On Tue, Mar 10, 2015 at 12:49 PM, Marc Millstone <millstone@gmail.com> wrote:
> > This looks great.  Is the 60$ per year per project? Per team?  Per company?
> >
> It is per "seat" per year, where a seat is either a developer or a
> continuous integration server. But there's also a clause in the
> license agreement that allows anyone to use it for free without a
> licence key, and in such cases it will operate with reduced features.
> That allows you to include SuperSafe in your build and just buy a
> license key for one developer if you want. Everyone else would just be
> running it in reduced feature mode. That one person might have to fix
> other people's bugs from time to time, but depending on how that goes
> it might be fine for some teams. The full legalese is here:
> http://www.artima.com/supersafe_license.html
>
> In the future we plan to offer a site license also, but we don't have
> that yet. Let me know if you have other questions.
>
> Bill
>
> > On Tue, Mar 10, 2015 at 12:31 PM, Bill Venners <bill@artima.com> wrote:
> >>
> >> Hi Marc,
> >>
> >> We'd like to invite you to try our latest software tool for Scala
> >> developers, Artima SuperSafe, free for thirty days. SuperSafe goes where no
> >> developer tool has gone before: it is the first compiler plugin that
> >> eliminates equality comparison bugs in Scala programs. It will save you time
> >> and money by ensuring certain kinds of defects don't escape past the compile
> >> phase. And to thank you for trying SuperSafe, we'll also give you a 50%
> >> discount coupon for Artima's Scala books.
> >>
> >> Even if you decide not to license SuperSafe long term, you can use it for
> >> a month for free to seek out bugs in your Scala projects. Just click on the
> >> big blue button on this page to download a license file (and get the
> >> discount on books):
> >>
> >> http://www.artima.com/supersafe_vip?n=0dWSsFO5GE
> >>
> >> Thanks.
> >>
> >> Bill
> >> ----
> >> Bill Venners
> >> President, Artima, Inc.
> >>
> >> You are receiving this email because you either subscribed to Artima
> >> Marketplace mailing list or made a Scala-related purchase at Artima.com
> >> under the Artima ID, 76402. You can edit your email preferences at the
> >> settings page of your Artima.com user account:
> >> http://www.artima.com/account, or you can unsubscribe from this mailing list
> >> here: http://www.artima.com/account/unsubscribe?n=08xI48G7FD.
> >>
> >> If you have any trouble unsubscribing via the above process, please email
> >> us at unsubscribe-help@artima.com and a real human being will make sure you
> >> get unsubscribed.
> >>
> >> Artima, Inc.
> >> 2070 N Broadway #305
> >> Walnut Creek, CA 94597, USA
> >> http://www.artima.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/socrata/socrata-sbt-plugins/issues/19>.
>



-- 
Evan Chan   |   Principal Engineer, Socrata     |    @evanfchan
*Socrata <http://www.socrata.com/> *| The Data Experience Company™
*Socrata isn't about worldly success, but about changing the world
successfully. This is why I'm excited to be here.*
*What does Socrata do? <https://www.youtube.com/watch?v=yyz86MlkriQ> *(watch
our 2 min video)

**Comment by sokrahta** [comment]
Artima SuperSafe says they
> add compiler errors for several kinds of bugs that aren't caught by type checker. 

1. prevents equality comparison and container-ship that are not sub-/super-class related, or cooperative, or `+GenSeq[T]`, or `+GenSet[T]`, or `+GenMap[T]`
1. prevents `AnyVal` compared to `null`
1. allows additional configured cooperative types
1. analyzes nested types
1. prevents `Array` equality comparison
1. optionally prevents equality comparison of specific types or any nested types
1. optionally prevents comparison of Java collections of cooperatives
1. prevents infix `equals`
1. prevent suspicious inferred type
1. support `Option.contains`
1. stricter invocation of `String` functions `contains`, `indexOf`, `lastIndexOf`
