### ISSUE TITLE
moar static analysis

### ISSUE THREAD

**Issue by sokrahta** [socrata-platform/socrata-sbt-plugins#28]
Some options to consider:

Scapegoat https://github.com/sksamuel/scalac-scapegoat-plugin
Wart remover https://github.com/typelevel/wartremover -> https://github.com/puffnfresh/wartremover
Linter https://github.com/HairyFotr/linter
CPD https://github.com/sbt/cpd4sbt
Abide https://github.com/scala/scala-abide
Findbugs https://github.com/sbt/findbugs4sbt
Alacs is no longer active https://github.com/ymasory/alacs

**Comment by velvia** [comment]
Abide is more limited than either WartRemover or ScalaStyle.
Not sure how active most of the other projects are.

On Thu, Jun 25, 2015 at 4:31 PM, John Krah <notifications@github.com> wrote:

> Some options to consider:
>
> Scapegoat https://github.com/sksamuel/scalac-scapegoat-plugin
> Wart remover https://github.com/typelevel/wartremover ->
> https://github.com/puffnfresh/wartremover
> Linter https://github.com/HairyFotr/linter
> CPD https://github.com/sbt/cpd4sbt
> Abide https://github.com/scala/scala-abide
> Findbugs https://github.com/sbt/findbugs4sbt
> Alacs is no longer active https://github.com/ymasory/alacs
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/socrata-platform/socrata-sbt-plugins/issues/28>.
>



-- 
Evan Chan   |   Principal Engineer, Socrata     |    @evanfchan
*Socrata <http://www.socrata.com/> *| The Data Experience Company™
*Socrata isn't about worldly success, but about changing the world
successfully. This is why I'm excited to be here.*
*What does Socrata do? <https://www.youtube.com/watch?v=yyz86MlkriQ> *(watch
our 2 min video)
