### ISSUE TITLE
scala idiomatic try

### ISSUE THREAD

**Issue by sokrahta** [socrata-platform/socrata-sbt-plugins#34]
Prefer `Try ... match Failure/Success` 
Avoid `try ... catch Exception`

**Comment by rjmac** [comment]
No; avoid `Try` unless you absolutely need it.  You almost never do.  `Try` should only be used when you're reifying a success or failure condition for someone else _who is not in your thread of control_ to handle.  If you're not doing that, `try`/`catch` is both more efficient and loses less type information.

**Comment by sokrahta** [comment]
thanks Robert :-)
