### ISSUE TITLE
compile flag: warn unused import

### ISSUE THREAD

**Issue by sokrahta** [socrata-platform/socrata-sbt-plugins#41]
@kaidamasaki  - So, Scala 2.11 adds a -Ywarn-unused-import flag, do you think that would be a good candidate to add to socrata-sbt-plugins?

**Comment by kaidamasaki** [comment]
Quite possibly.  

There are a few issues: 

1. You have to remove the compiler flag for the console, or you can't do any imports (which definitely shouldn't be the behavior of that compiler flag, but whatever...), which isn't that tricky, but is a little annoying.

2. Anyone that upgraded to this version of the plugin would need to fix all of their unused imports, which probably means lots of them.

**Comment by sokrahta** [comment]
@aerust @jacobsi - unused imports are going in here, I just researched and found out how to address kaida's #1 concern. and for #1 it's only a warning anyway.
